import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useLogin, useMe, useRead, useSignup } from "../src/hooks";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data: me } = useMe();
  const { data: userData } = useRead(14);
  const { signup, isLoading: sginupLoading } = useSignup();
  const { login, isLoading: loginLoding } = useLogin();

  console.log("내 정보입니다", me);
  console.log("14번 유저입니다.", userData);

  const handleSginup = () => {
    if (sginupLoading) return;
    signup({
      email: "hgs_0529@naver.com",
      password: "123",
      name: "황길성",
      phoneNumber: "010-0000-0000",
      agreements: { privacy: true, ad: false },
    });
  };

  const handleLogin = () => {
    if (loginLoding) return;
    login({ email: "hgs_0529@naver.com", password: "123" });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>NUMBLE:: 쿠팡 클론</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello World!</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>src/services</code>,
          <code className={styles.code}>src/hooks</code>
        </p>
        <button type="button" onClick={handleSginup}>
          회원가입
        </button>
        <button type="button" onClick={handleLogin}>
          로그인
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/numble.png" alt="NUMBLE Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
